Question_City1 = [["Question for City 1 Number:1","AA1","AB1","AC1","AD1"],
                    ["Question for City 1 Number:2","AA2","AB2","AC2","AD2"],
                    ["Question for City 1 Number:3","AA3","AB3","AC3","AD3"],
                    ["Question for City 1 Number:4","AA4","AB4","AC4","AD4"],
                    ["Question for City 1 Number:5","AA5","AB5","AC5","AD5"],
                    ["Question for City 1 Number:6","AA6","AB6","AC6","AD6"],
                    ["Question for City 1 Number:7","AA7","AB7","AC7","AD7"],
                    ["Question for City 1 Number:8","AA8","AB8","AC8","AD8"],
                    ["Question for City 1 Number:9","AA9","AB9","AC9","AD9"],
                    ["Question for City 1 Number:10","AA10","AB10","AC10","AD10"],
                    ["Question for City 1 Number:11","AA11","AB11","AC11","AD11"],
                    ["Question for City 1 Number:12","AA12","AB12","AC12","AD12"],
                    ["Question for City 1 Number:13","AA13","AB13","AC13","AD13"]]
Question_City2 = [["Question for City 2 Number:1","AA1","AB1","AC1","AD1"],
                    ["Question for City 2 Number:2","AA2","AB2","AC2","AD2"],
                    ["Question for City 2 Number:3","AA3","AB3","AC3","AD3"],
                    ["Question for City 2 Number:4","AA4","AB4","AC4","AD4"],
                    ["Question for City 2 Number:5","AA5","AB5","AC5","AD5"],
                    ["Question for City 2 Number:6","AA6","AB6","AC6","AD6"],
                    ["Question for City 2 Number:7","AA7","AB7","AC7","AD7"],
                    ["Question for City 2 Number:8","AA8","AB8","AC8","AD8"],
                    ["Question for City 2 Number:9","AA9","AB9","AC9","AD9"],
                    ["Question for City 2 Number:10","AA10","AB10","AC10","AD10"],
                    ["Question for City 2 Number:11","AA11","AB11","AC11","AD11"],
                    ["Question for City 2 Number:12","AA12","AB12","AC12","AD12"],
                    ["Question for City 2 Number:13","AA13","AB13","AC13","AD13"]]
Question_City3 = [["Question for City 3 Number:1","AA1","AB1","AC1","AD1"],
                    ["Question for City 3 Number:2","AA2","AB2","AC2","AD2"],
                    ["Question for City 3 Number:3","AA3","AB3","AC3","AD3"],
                    ["Question for City 3 Number:4","AA4","AB4","AC4","AD4"],
                    ["Question for City 3 Number:5","AA5","AB5","AC5","AD5"],
                    ["Question for City 3 Number:6","AA6","AB6","AC6","AD6"],
                    ["Question for City 3 Number:7","AA7","AB7","AC7","AD7"],
                    ["Question for City 3 Number:8","AA8","AB8","AC8","AD8"],
                    ["Question for City 3 Number:9","AA9","AB9","AC9","AD9"],
                    ["Question for City 3 Number:10","AA10","AB10","AC10","AD10"],
                    ["Question for City 3 Number:11","AA11","AB11","AC11","AD11"],
                    ["Question for City 3 Number:12","AA12","AB12","AC12","AD12"],
                    ["Question for City 3 Number:13","AA13","AB13","AC13","AD13"]]
# [Question,{'A':'ChoiceA','B':'ChoiceB','C':'ChoiceC','D':'ChoiceD'},CorrectAnswer]
Question_Total = [[["Question for City 1 Number:1",{'A':"A11",'B':"B11",'C':"C11",'D':"D11"},"C11"], #end of question1 for city1
                    ["Question for City 1 Number:2",{'A':"A12",'B':"B12",'C':"C12",'D':"D12"},"C12"],
                    ["Question for City 1 Number:3",{'A':"A13",'B':"B13",'C':"C13",'D':"D13"},"D13"],
                    ["Question for City 1 Number:4",{'A':"A14",'B':"B14",'C':"C14",'D':"D14"},"A14"]], #end of city 1
                    [["Question for City 2 Number:1",{'A':"A21",'B':"B21",'C':"C21",'D':"D21"},"C21"],
                    ["Question for City 2 Number:2",{'A':"A22",'B':"B22",'C':"C22",'D':"D22"},"C22"],
                    ["Question for City 2 Number:3",{'A':"A23",'B':"B23",'C':"C23",'D':"D23"},"D23"],
                    ["Question for City 2 Number:4",{'A':"A24",'B':"B24",'C':"C24",'D':"D24"},"A24"]], #end of city 2
                    [["Question for City 3 Number:1","AA1","AB1","AC1","AD1"],
                    ["Question for City 3 Number:2","AA2","AB2","AC2","AD2"],
                    ["Question for City 3 Number:3","AA3","AB3","AC3","AD3"],
                    ["Question for City 3 Number:4","AA4","AB4","AC4","AD4"]],
                    [["Question for City 4 Number:1","AA1","AB1","AC1","AD1"],
                    ["Question for City 4 Number:2","AA2","AB2","AC2","AD2"],
                    ["Question for City 4 Number:3","AA3","AB3","AC3","AD3"],
                    ["Question for City 4 Number:4","AA4","AB4","AC4","AD4"]],
                    [["Question for City 5 Number:1","AA1","AB1","AC1","AD1"],
                    ["Question for City 5 Number:2","AA2","AB2","AC2","AD2"],
                    ["Question for City 5 Number:3","AA3","AB3","AC3","AD3"],
                    ["Question for City 5 Number:4","AA4","AB4","AC4","AD4"]],
                    [["Question for City 6 Number:1","AA1","AB1","AC1","AD1"],
                    ["Question for City 6 Number:2","AA2","AB2","AC2","AD2"],
                    ["Question for City 6 Number:3","AA3","AB3","AC3","AD3"],
                    ["Question for City 6 Number:4","AA4","AB4","AC4","AD4"]]]
